spring:
  application:
    name: book-management
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
  flyway:
    enabled: true